---
name: pre-commit
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Run pre-commit checks
        uses: saritasa-nest/saritasa-github-actions/.github/actions/pre-commit@5adb8c6d94bf4ae686a32eb5cee3207b57f455bc # v4.1
        with:
          ignore-commit-authors: github-actions
          node-version: '20'
          python-version: '3.x'
          tools-list: |
            terraform-docs=https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
