---
name: terraform-module-release
on:
  pull_request:
    # Requires 'closed' to trigger the release process when the PR is merged
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  # Required for pushing tags, creating releases, and updating the repository
  contents: write
  # Required to comment on the pull request with release details
  pull-requests: write
jobs:
  # ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
  # │   TERRAFORM MODULE RELEASE JOB                                                                                     │
  # │   ---                                                                                                              │
  # │                                                                                                                    │
  # │   The 'release' job checks out code from the repository and uses the `terraform-module-releaser` action that       │
  # │   creates proper tags and releases for every affected Terraform module, based on commit messages.                  |
  # |   It follows Semantic Versioning (SemVer) and Conventional Commits to determine the release type (major, minor,    |
  # |   patch).                                                                                                          |
  # │   For example, if the commit message contains "fix: correct variable name in main.tf" the action will detect it    |
  # |   as a patch change and increment the affected Terraform module's Git tag version from v0.0.3 to v0.0.4.           │
  # │                                                                                                                    |
  # |   For each changed terraform module job creates an isolated commit that only has the .tf codes of that module,     |
  # |   with an exception of `examples/usage.tf` file.                                                                   |
  # |   Example of a commit:                                                                                             |
  # |   https://github.com/saritasa-nest/test-terraform-module-releaser/tree/1dba18af48bfd9f458ac86fa1d7533ee19351f46    |
  # │                                                                                                                    │
  # └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release new Terraform module version
        uses: techpivot/terraform-module-releaser@v1.5.0
        id: terraform-module-release
        with:
          # Keywords indicating a major version bump (from 1.x.x to 2.0.0)
          # Example: `breaking-change: remove deprecated module SD-373`
          major-keywords: 'update:,breaking-change:'
          # Keywords indicating a minor version bump (from x.1.x to x.2.0)
          # Example: `feat: add dynamic resource provisioning SD-373`
          minor-keywords: 'feat:,feature:'
          # Keywords indicating a patch version bump (from x.x.1 to x.x.2)
          # Example: `fix: correct typo in variable name in main.tf SD-373`
          patch-keywords: 'fix:,chore:,docs:,patch:'
          default-first-tag: v0.0.1
          # Whether tags and releases from Terraform modules that have been deleted should be automatically removed
          delete-legacy-tags: false
          # Whether to disable wiki generation for Terraform modules
          disable-wiki: false
          # Module paths to completely ignore
          module-path-ignore: '**/examples'
          # File patterns to exclude from triggering version changes in Terraform modules
          module-change-exclude-patterns: '!*.tf, examples/**'
          # File patterns to exclude when bundling a Terraform module for tag/release
          module-asset-exclude-patterns: '!*.tf, examples/**'
